// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"lottery-go/internal/application"
	"lottery-go/internal/contract"
	"lottery-go/internal/job"
	"lottery-go/internal/server"
)

// Injectors from wire.go:

func initApp() (*server.App, error) {
	dailyLotteryContract := contract.NewDailyLotteryContract()
	dailyLotteryApplication := application.NewDailyLotteryApplication(dailyLotteryContract)
	drawLotteryJob := job.NewDrawLotteryJob(dailyLotteryApplication)
	registryJobs := job.NewRegistryJobs(drawLotteryJob)
	cron, err := server.NewJob(registryJobs)
	if err != nil {
		return nil, err
	}
	app := server.NewApp(cron)
	return app, nil
}
