import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { type ReactNode } from "react";
import "./globals.css";

import { Toaster } from "react-hot-toast";
import { Providers } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "去中心化彩票系统",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
